---
output: false
echo: true                      # set to true to show solution
code-fold: true
code-summary: "Musterlösung"    
---

# Übung 1 {#sec-aufgabe1}

:::{#tip-new-file .callout-tip}

Um diese Übung zu lösen, erstellt ihr am besten ein neues Python File (⨁ New → New File → Python File) und speichert dies direkt ab.

:::

<!-- % Variablen erstellen -->
## Übung 1.1

Erstelle eine Variabel `vorname` mit deinem Vornamen und eine zweite Variabel `nachname` mit deinem Nachnamen.  Was sind `vorname` und `nachname` für Datentypen?


```{python}
vorname = "Guido"
nachname = "van Rossum"

type(vorname) # es handelt sich um den Datentyp "str", also String (Text)   
```

## Übung 1.2

"Klebe" Vor- und Nachname mit einem Leerschlag dazwischen zusammen.

```{python}
vorname + " " + nachname
```

## Übung 1.3

Erstelle eine Variabel `groesse_cm` mit deiner Körpergrösse in Zentimeter. Was ist das für ein Datentyp?

```{python}
groesse_cm = 184
type(groesse_cm) # es handelt sich hierbei um den Datentyp "integer"
```

## Übung 1.4

Ermittle deine Grösse in Fuss auf der Basis von `groesse_cm` (1 Fuss entspricht 30.48 cm). Was ist das für ein Datentyp?

```{python}
groesse_fuss = groesse_cm / 30.48
type(groesse_fuss) # es handelt sich um den Datentyp "float"
```

## Übung 1.5

Erstelle eine boolsche Variable blond und setzte sie auf `True`, wenn diese Eigenschaft auf dich zutrifft, und `False`, falls nicht. 

```{python}
blond = False
```

## Übung 1.6

Erstelle eine Variabel `einwohner` mit der Einwohnerzahl der Schweiz (8'603'900, per 31. Dezember 2019). Erstelle eine zweite Variabel `flaeche` (ohne Umlaute!) mit der Flächengrösse der Schweiz (41'285 km$^2$). Berechne nun die Einwohnerdichte.

```{python}
einwohner = 8603900
flaeche = 41285

dichte = einwohner / flaeche

dichte
```

## Übung 1.7

Erstelle eine Variabel `gewicht_kg` (kg) und `groesse_m` (m) und berechne aufgrund von `gewicht_kg` und `groesse_m` ein BodyMassIndex ($BMI=\frac{m}{l^2}$, $m$: Körpermasse in Kilogramm, $l$: Körpergrösse in Meter).

```{python}
gewicht_kg = 85
groesse_m = groesse_cm / 100

gewicht_kg / (groesse_m * groesse_m)
```
